name: smart_trash_can
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
  #sdk: '>=3.0.0-63.0.dev <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #conditional_builder: ^1.0.2
  #bloc: ^8.1.0
  #bloc_provider: ^1.0.0
  #flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  fluttertoast: ^8.1.1
  icon_broken: ^1.1.0
  pin_code_fields: ^7.4.0


    #firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  #firebase_storage: ^11.0.10
  #firebase_messaging: ^14.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  
  assets:
    - assets/
  fonts:
    - family: Anaqa
      fonts:
        - asset: assets/Anaqa-Semibold.ttf
